import { List, fromJS } from "immutable";

export default bookPaths = {
  Genesis: fromJS(require("./Genesis.json")),
  Exodus: fromJS(require("./Exodus.json")),
  Leviticus: fromJS(require("./Leviticus.json")),
  Numbers: fromJS(require("./Numbers.json")),
  Deuteronomy: fromJS(require("./Deuteronomy.json")),
  Joshua: fromJS(require("./Joshua.json")),
  Judges: fromJS(require("./Judges.json")),
  Ruth: fromJS(require("./Ruth.json")),
  "I Samuel": fromJS(require("./1 Samuel.json")),
  "II Samuel": fromJS(require("./2 Samuel.json")),
  "I Kings": fromJS(require("./1 Kings.json")),
  "II Kings": fromJS(require("./2 Kings.json")),
  "I Chronicles": fromJS(require("./1 Chronicles.json")),
  "II Chronicles": fromJS(require("./2 Chronicles.json")),
  Ezra: fromJS(require("./Ezra.json")),
  Nehemiah: fromJS(require("./Nehemiah.json")),
  Esther: fromJS(require("./Esther.json")),
  Job: fromJS(require("./Job.json")),
  Psalms: fromJS(require("./Psalms.json")),
  Proverbs: fromJS(require("./Proverbs.json")),
  Ecclesiastes: fromJS(require("./Ecclesiastes.json")),
  "Song of Solomon": fromJS(require("./Song of Solomon.json")),
  Isaiah: fromJS(require("./Isaiah.json")),
  Jeremiah: fromJS(require("./Jeremiah.json")),
  Lamentations: fromJS(require("./Lamentations.json")),
  Ezekiel: fromJS(require("./Ezekiel.json")),
  Daniel: fromJS(require("./Daniel.json")),
  Hosea: fromJS(require("./Hosea.json")),
  Joel: fromJS(require("./Joel.json")),
  Amos: fromJS(require("./Amos.json")),
  Obadiah: fromJS(require("./Obadiah.json")),
  Jonah: fromJS(require("./Jonah.json")),
  Micah: fromJS(require("./Micah.json")),
  Nahum: fromJS(require("./Nahum.json")),
  Habakkuk: fromJS(require("./Habakkuk.json")),
  // Zephaniah: fromJS(require("./Zephaniah.json")),
  Haggai: fromJS(require("./Haggai.json")),
  // Zechariah: fromJS(require("./Zechariah.json")),
  Malachi: fromJS(require("./Malachi.json")),
  Matthew: fromJS(require("./Matthew.json")),
  Mark: fromJS(require("./Mark.json")),
  Luke: fromJS(require("./Luke.json")),
  John: fromJS(require("./John.json")),
  Acts: fromJS(require("./Acts.json")),
  Romans: fromJS(require("./Romans.json")),
  "I Corinthians": fromJS(require("./1 Corinthians.json")),
  "II Corinthians": fromJS(require("./2 Corinthians.json")),
  Galatians: fromJS(require("./Galatians.json")),
  Ephesians: fromJS(require("./Ephesians.json")),
  Philippians: fromJS(require("./Philippians.json")),
  Colossians: fromJS(require("./Colossians.json")),
  "I Thessalonians": fromJS(require("./1 Thessalonians.json")),
  "II Thessalonians": fromJS(require("./2 Thessalonians.json")),
  "I Timothy": fromJS(require("./1 Timothy.json")),
  "II Timothy": fromJS(require("./2 Timothy.json")),
  // Titus: fromJS(require("./Titus.json")),
  Philemon: fromJS(require("./Philemon.json")),
  Hebrews: fromJS(require("./Hebrews.json")),
  James: fromJS(require("./James.json")),
  "I Peter": fromJS(require("./1 Peter.json")),
  "II Peter": fromJS(require("./2 Peter.json")),
  "I John": fromJS(require("./1 John.json")),
  "II John": fromJS(require("./2 John.json")),
  "III John": fromJS(require("./3 John.json")),
  Jude: fromJS(require("./Jude.json")),
  Revelation: fromJS(require("./Revelation.json")),
};
