export default bookPaths = {
  Genesis: require("./Genesis.json"),
  Exodus: require("./Exodus.json"),
  Leviticus: require("./Leviticus.json"),
  Numbers: require("./Numbers.json"),
  Deuteronomy: require("./Deuteronomy.json"),
  Joshua: require("./Joshua.json"),
  Judges: require("./Judges.json"),
  Ruth: require("./Ruth.json"),
  "I Samuel": require("./1 Samuel.json"),
  "II Samuel": require("./2 Samuel.json"),
  "I Kings": require("./1 Kings.json"),
  "II Kings": require("./2 Kings.json"),
  "I Chronicles": require("./1 Chronicles.json"),
  "II Chronicles": require("./2 Chronicles.json"),
  Ezra: require("./Ezra.json"),
  Nehemiah: require("./Nehemiah.json"),
  Esther: require("./Esther.json"),
  Job: require("./Job.json"),
  Psalms: require("./Psalms.json"),
  Proverbs: require("./Proverbs.json"),
  Ecclesiastes: require("./Ecclesiastes.json"),
  "Song of Solomon": require("./Song of Solomon.json"),
  Isaiah: require("./Isaiah.json"),
  Jeremiah: require("./Jeremiah.json"),
  Lamentations: require("./Lamentations.json"),
  Ezekiel: require("./Ezekiel.json"),
  Daniel: require("./Daniel.json"),
  Hosea: require("./Hosea.json"),
  Joel: require("./Joel.json"),
  Amos: require("./Amos.json"),
  Obadiah: require("./Obadiah.json"),
  Jonah: require("./Jonah.json"),
  Micah: require("./Micah.json"),
  Nahum: require("./Nahum.json"),
  Habakkuk: require("./Habakkuk.json"),
  // Zephaniah: require("./Zephaniah.json"),
  Haggai: require("./Haggai.json"),
  // Zechariah: require("./Zechariah.json"),
  Malachi: require("./Malachi.json"),
  Matthew: require("./Matthew.json"),
  Mark: require("./Mark.json"),
  Luke: require("./Luke.json"),
  John: require("./John.json"),
  Acts: require("./Acts.json"),
  Romans: require("./Romans.json"),
  "I Corinthians": require("./1 Corinthians.json"),
  "II Corinthians": require("./2 Corinthians.json"),
  Galatians: require("./Galatians.json"),
  Ephesians: require("./Ephesians.json"),
  Philippians: require("./Philippians.json"),
  Colossians: require("./Colossians.json"),
  "I Thessalonians": require("./1 Thessalonians.json"),
  "II Thessalonians": require("./2 Thessalonians.json"),
  "I Timothy": require("./1 Timothy.json"),
  "II Timothy": require("./2 Timothy.json"),
  // Titus: require("./Titus.json"),
  Philemon: require("./Philemon.json"),
  Hebrews: require("./Hebrews.json"),
  James: require("./James.json"),
  "I Peter": require("./1 Peter.json"),
  "II Peter": require("./2 Peter.json"),
  "I John": require("./1 John.json"),
  "II John": require("./2 John.json"),
  "III John": require("./3 John.json"),
  Jude: require("./Jude.json"),
  Revelation: require("./Revelation.json"),
};
